site_name: Cosmosys Documentation
site_url: https://hyperb1iss.github.io/cosmosys
site_author: Stefanie Jane
site_description: Documentation for Cosmosys, a stellar release management tool.

repo_name: hyperb1iss/cosmosys
repo_url: https://github.com/hyperb1iss/cosmosys
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: material/rocket-launch
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - social
  - tags
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
  - glightbox:
      auto_caption: true
      caption_position: bottom

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hyperb1iss/cosmosys
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cosmosys/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cosmosys
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
  - Core Concepts:
    - Release Process: release-process.md
    - Advanced Configuration: advanced.md
    - Theming: theming.md
    - Plugins: plugins.md
  - API Reference:
    - Core: api/core.md
    - Plugins: api/plugins.md
  - Community:
    - Contributing: contributing.md
    - Community Guidelines: community-guidelines.md
  - Help:
    - Troubleshooting & FAQs: troubleshooting.md
    - Getting Support: support.md
  - Changelog: changelog.md

copyright: Copyright &copy; 2024 Stefanie Jane

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js